module.exports =
  [
    {"id" : "1","name" : "Earthshaker","icon" : "http://cdn.dota2.com/apps/dota2/images/heroes/earthshaker_sb.png?v=4018248","banner" : "","team": "sentinel","attr": "strength"},
    {"id" : "3","name" : "Sven","icon" : "http://cdn.dota2.com/apps/dota2/images/heroes/sven_sb.png?v=4018248","banner" : "","team": "sentinel","attr": "strength"},
    {"id" : "4","name" : "Tiny","icon" : "http://cdn.dota2.com/apps/dota2/images/heroes/tiny_sb.png?v=4018248","banner" : "","team": "sentinel","attr": "strength"},
    {"id" : "5","name" : "Kunkka","icon" : "http://cdn.dota2.com/apps/dota2/images/heroes/kunkka_sb.png?v=4018248","banner" : "","team": "sentinel","attr": "strength"},
    {"id" : "6","name" : "Beastmaster","icon" : "http://cdn.dota2.com/apps/dota2/images/heroes/beastmaster_sb.png?v=4018248","banner" : "","team": "sentinel","attr": "strength"},
    {"id" : "8","name" : "Dragon Knight","icon" : "http://cdn.dota2.com/apps/dota2/images/heroes/dragon_knight_sb.png?v=4018248","banner" : "","team": "sentinel","attr": "strength"},
    {"id" : "9","name" : "Clockwerk","icon" : "http://cdn.dota2.com/apps/dota2/images/heroes/rattletrap_sb.png?v=4018248","banner" : "","team": "sentinel","attr": "strength"},
    {"id" : "10","name" : "Omniknight","icon" : "http://cdn.dota2.com/apps/dota2/images/heroes/omniknight_sb.png?v=4018248","banner" : "","team": "sentinel","attr": "strength"},
    {"id" : "11","name" : "Huskar","icon" : "http://cdn.dota2.com/apps/dota2/images/heroes/huskar_sb.png?v=4018248","banner" : "","team": "sentinel","attr": "strength"},
    {"id" : "12","name" : "Alchemist","icon" : "http://cdn.dota2.com/apps/dota2/images/heroes/alchemist_sb.png?v=4018248","banner" : "","team": "sentinel","attr": "strength"},
    {"id" : "13","name" : "Brewmaster","icon" : "http://cdn.dota2.com/apps/dota2/images/heroes/brewmaster_sb.png?v=4018248","banner" : "","team": "sentinel","attr": "strength"},
    {"id" : "14","name" : "Treant Protector","icon" : "http://cdn.dota2.com/apps/dota2/images/heroes/treant_sb.png?v=4018248","banner" : "","team": "sentinel","attr": "strength"},
    {"id" : "23","name" : "Io","icon" : "http://localhost:8868/images/heroes/io_sb.png?v=4018248","banner" : "","team": "sentinel","attr": "strength"},
    {"id" : "16","name" : "Centaur Warrunner","icon" : "http://cdn.dota2.com/apps/dota2/images/heroes/centaur_sb.png?v=4018248","banner" : "","team": "sentinel","attr": "strength"},
    {"id" : "17","name" : "Timbersaw","icon" : "http://cdn.dota2.com/apps/dota2/images/heroes/shredder_sb.png?v=4018248","banner" : "","team": "sentinel","attr": "strength"},
    {"id" : "18","name" : "Bristleback","icon" : "http://cdn.dota2.com/apps/dota2/images/heroes/bristleback_sb.png?v=4018248","banner" : "","team": "sentinel","attr": "strength"},
    {"id" : "19","name" : "Tuskar","icon" : "http://cdn.dota2.com/apps/dota2/images/heroes/tusk_sb.png?v=4018248","banner" : "","team": "sentinel","attr": "strength"},
    {"id" : "20","name" : "Elder Titan","icon" : "http://cdn.dota2.com/apps/dota2/images/heroes/elder_titan_sb.png?v=4018248","banner" : "","team": "sentinel","attr": "strength"},
    {"id" : "2","name" : "Legion Commander","icon" : "http://localhost:8868/images/heroes/legion_commander_arc.png","banner" : "http://localhost:8868/images/heroes/banner/Blades_of_Voth_Domosh.jpg","team": "sentinel","attr": "strength"},
    {"id" : "21","name" : "Earth Spirit","icon" : "http://cdn.dota2.com/apps/dota2/images/heroes/earth_spirit_sb.png?v=4018248","banner" : "","team": "sentinel","attr": "strength"},
    {"id" : "38","name" : "Phoenix","icon" : "http://cdn.dota2.com/apps/dota2/images/heroes/phoenix_sb.png?v=4018248","banner" : "","team": "sentinel","attr": "strength"},
    {"id" : "22","name" : "Axe","icon" : "http://cdn.dota2.com/apps/dota2/images/heroes/axe_sb.png?v=4018248","banner" : "","team": "scourge","attr": "strength"},
    {"id" : "23","name" : "Pudge","icon" : "http://cdn.dota2.com/apps/dota2/images/heroes/pudge_sb.png?v=4018248","banner" : "","team": "scourge","attr": "strength"},
    {"id" : "24","name" : "Sand King","icon" : "http://cdn.dota2.com/apps/dota2/images/heroes/sand_king_sb.png?v=4018248","banner" : "","team": "scourge","attr": "strength"},
    {"id" : "25","name" : "Slardar","icon" : "http://cdn.dota2.com/apps/dota2/images/heroes/slardar_sb.png?v=4018248","banner" : "","team": "scourge","attr": "strength"},
    {"id" : "26","name" : "Tidehunter","icon" : "http://cdn.dota2.com/apps/dota2/images/heroes/tidehunter_sb.png?v=4018248","banner" : "","team": "scourge","attr": "strength"},
    {"id" : "27","name" : "Wraith King","icon" : "http://cdn.dota2.com/apps/dota2/images/heroes/skeleton_king_sb.png?v=4018248","banner" : "","team": "scourge","attr": "strength"},
    {"id" : "28","name" : "Lifestealer","icon" : "http://cdn.dota2.com/apps/dota2/images/heroes/life_stealer_sb.png?v=4018248","banner" : "","team": "scourge","attr": "strength"},
    {"id" : "29","name" : "Night Stalker","icon" : "http://cdn.dota2.com/apps/dota2/images/heroes/night_stalker_sb.png?v=4018248","banner" : "","team": "scourge","attr": "strength"},
    {"id" : "30","name" : "Doom Bringer","icon" : "http://cdn.dota2.com/apps/dota2/images/heroes/doom_bringer_sb.png?v=4018248","banner" : "","team": "scourge","attr": "strength"},
    {"id" : "31","name" : "Spirit Breaker","icon" : "http://cdn.dota2.com/apps/dota2/images/heroes/spirit_breaker_sb.png?v=4018248","banner" : "","team": "scourge","attr": "strength"},
    {"id" : "32","name" : "Lycan","icon" : "http://cdn.dota2.com/apps/dota2/images/heroes/lycan_sb.png?v=4018248","banner" : "","team": "scourge","attr": "strength"},
    {"id" : "33","name" : "Chaos Knight","icon" : "http://cdn.dota2.com/apps/dota2/images/heroes/chaos_knight_sb.png?v=4018248","banner" : "","team": "scourge","attr": "strength"},
    {"id" : "34","name" : "Undying","icon" : "http://cdn.dota2.com/apps/dota2/images/heroes/undying_sb.png?v=4018248","banner" : "","team": "scourge","attr": "strength"},
    {"id" : "35","name" : "Magnus","icon" : "http://cdn.dota2.com/apps/dota2/images/heroes/magnataur_sb.png?v=4018248","banner" : "","team": "scourge","attr": "strength"},
    {"id" : "36","name" : "Abaddon","icon" : "http://cdn.dota2.com/apps/dota2/images/heroes/abaddon_sb.png?v=4018248","banner" : "","team": "scourge","attr": "strength"},
    {"id" : "37","name" : "Underlord","icon" : "http://cdn.dota2.com/apps/dota2/images/heroes/abyssal_underlord_sb.png?v=4018248","banner" : "","team": "scourge","attr": "strength"},
    {"id" : "7","name" : "Phantom Assassin","icon" : "http://localhost:8868/images/heroes/phantom_assassin_arc.png","banner" : "http://localhost:8868/images/heroes/banner/Manifold_Paradox.jpg","team": "scourge","attr": "agility"},
    {"id" : "15","name" : "Puck","icon" : "http://cdn.dota2.com/apps/dota2/images/heroes/puck_sb.png?v=4018248","banner" : "","team": "sentinel","attr": "intelligence"}
  ];
